-- Teal's Sunday Pick'em v0.1.1 — Gate 1 Foundation
-- Shared-Supabase edition: run once in the EXISTING Yahtzee Supabase project.
-- This creates a separate `pickem` schema and does not alter Yahtzee public tables.

create extension if not exists pgcrypto;

create schema if not exists pickem;

-- The Streamlit server uses the service-role key. Normal browser roles get no access.
grant usage on schema pickem to service_role;
revoke all on schema pickem from anon, authenticated;

create table if not exists pickem.app_meta (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

insert into pickem.app_meta(key, value)
values ('schema_version', '{"version":"0.1.1"}'::jsonb)
on conflict (key) do update set value = excluded.value, updated_at = now();

create table if not exists pickem.players (
  id uuid primary key default gen_random_uuid(),
  nickname text not null,
  nickname_key text not null unique,
  emoji text not null,
  pin_salt text not null,
  pin_hash text not null,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists pickem.player_sessions (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references pickem.players(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz
);

create index if not exists player_sessions_player_idx on pickem.player_sessions(player_id);
create index if not exists player_sessions_expiry_idx on pickem.player_sessions(expires_at) where revoked_at is null;

create table if not exists pickem.login_attempts (
  id bigint generated by default as identity primary key,
  nickname_key text not null,
  success boolean not null,
  attempted_at timestamptz not null default now()
);

create index if not exists login_attempts_window_idx on pickem.login_attempts(nickname_key, attempted_at desc);

-- Defense in depth: enable RLS even though only service_role receives table privileges.
alter table pickem.app_meta enable row level security;
alter table pickem.players enable row level security;
alter table pickem.player_sessions enable row level security;
alter table pickem.login_attempts enable row level security;

revoke all on table pickem.app_meta from anon, authenticated;
revoke all on table pickem.players from anon, authenticated;
revoke all on table pickem.player_sessions from anon, authenticated;
revoke all on table pickem.login_attempts from anon, authenticated;

grant all on table pickem.app_meta to service_role;
grant all on table pickem.players to service_role;
grant all on table pickem.player_sessions to service_role;
grant all on table pickem.login_attempts to service_role;
grant usage, select on all sequences in schema pickem to service_role;

-- Ensure future Gate migrations in this schema remain server-only by default.
alter default privileges for role postgres in schema pickem revoke all on tables from anon, authenticated;
alter default privileges for role postgres in schema pickem revoke all on sequences from anon, authenticated;
alter default privileges for role postgres in schema pickem grant all on tables to service_role;
alter default privileges for role postgres in schema pickem grant usage, select on sequences to service_role;

-- No plaintext PINs, no plaintext persistent session tokens.
comment on column pickem.players.pin_hash is 'PBKDF2 hash; app also uses a server-side pepper.';
comment on column pickem.player_sessions.token_hash is 'HMAC-SHA256 of opaque remembered-device token.';
